services:

  postgres:
    image: postgres:17
    container_name: ticketing-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: ticketing-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TicketingDb: Host=postgres;Port=5432;Database=ticketing;Username=postgres;Password=postgres
    volumes:
      - ./backend:/app
    working_dir: /app
    command: dotnet watch --project ./Ticketing.API/Ticketing.API.csproj run --urls http://0.0.0.0:8080
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: ticketing-front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev -- --host 0.0.0.0 --port 5173

  mobile:
    image: node:20
    container_name: ticketing-mobile
    working_dir: /app
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_NATIVE_PACKAGER_HOSTNAME: "192.168.1.23"
    command: sh -c "npm install && npx expo start --host lan --clear"

volumes:
  db-data: