services:

  postgres:
    image: postgres:17
    container_name: ticketing-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
      TZ: America/Montevideo
      PGTZ: America/Montevideo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

  backend:
    build: ./backend
    container_name: ticketing-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__TicketingDb: Host=postgres;Port=5432;Database=ticketing;Username=postgres;Password=postgres
      ConnectionStrings__TicketingDb_Usuario: Host=postgres;Port=5432;Database=ticketing;Username=app_usuario;Password=pwd_usuario
      ConnectionStrings__TicketingDb_Funcionario: Host=postgres;Port=5432;Database=ticketing;Username=app_funcionario;Password=pwd_funcionario
      ConnectionStrings__TicketingDb_Admin: Host=postgres;Port=5432;Database=ticketing;Username=app_admin;Password=pwd_admin
    volumes:
      - ./backend:/app
    working_dir: /app
    command: dotnet watch --project ./Ticketing.API/Ticketing.API.csproj run --urls http://0.0.0.0:8080
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: ticketing-front
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  db-data: